from app.config import (
    LEDGER_QUORUM_SIZE,
    MULTI_RELAY_MODE,
    PEER_RELAYS,
    RELAY_AUTO_EXIT_JOIN_MODE_ON_SYNC,
    RELAY_DOMAIN,
    RELAY_JOIN_BLOCK_CLIENT_WRITES,
    RELAY_JOIN_MODE,
    RELAY_MAX_SYNC_CLIENTS,
    RELAY_SYNC_SOURCE_WEIGHT,
)

NETWORK_ID = "blankchat-mainnet-v1"
VALIDATOR_SET_VERSION = 1

THIS_RELAY_DOMAIN = RELAY_DOMAIN
QUORUM_SIZE = LEDGER_QUORUM_SIZE
IS_MULTI_RELAY_MODE = MULTI_RELAY_MODE
VALIDATOR_PEERS = PEER_RELAYS

SYNC_SOURCE_WEIGHT = RELAY_SYNC_SOURCE_WEIGHT
MAX_SYNC_CLIENTS = RELAY_MAX_SYNC_CLIENTS
BLOCK_CLIENT_WRITES_WHILE_SYNCING = RELAY_JOIN_BLOCK_CLIENT_WRITES

IS_JOIN_MODE = RELAY_JOIN_MODE
AUTO_EXIT_JOIN_MODE_ON_SYNC = RELAY_AUTO_EXIT_JOIN_MODE_ON_SYNC


def get_peer_domains() -> list[str]:
    return VALIDATOR_PEERS
